import io
import gzip
import xml.etree.ElementTree as ET
from xml.dom import minidom
from datetime import datetime, timezone
from urllib.parse import urlparse
import pandas as pd

def build_xml_sitemap(
    pages: list,
    default_changefreq: str = "weekly",
    auto_priority: bool = True,
    fixed_priority: str = None,
    auto_lastmod: bool = True
) -> str:
    """
    Generate official Google / W3C standard XML sitemap string conforming to sitemaps.org schema.
    Only includes valid 200 OK indexable pages.
    """
    urlset = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    for page in pages:
        url = str(page.get("url", "")).strip()
        if not url:
            continue

        # Filter: Only 200 OK and Indexable pages belong in a clean XML Sitemap!
        status = page.get("status_code", 200)
        is_indexable = page.get("is_indexable", True)
        if status != 200 or is_indexable is False:
            continue

        url_elem = ET.SubElement(urlset, "url")
        
        # 1. <loc>
        loc_elem = ET.SubElement(url_elem, "loc")
        loc_elem.text = url

        # 2. <lastmod>
        if auto_lastmod:
            lastmod_elem = ET.SubElement(url_elem, "lastmod")
            lastmod_elem.text = today_str

        # 3. <changefreq>
        if default_changefreq and default_changefreq.lower() != "do not include":
            changefreq_elem = ET.SubElement(url_elem, "changefreq")
            changefreq_elem.text = default_changefreq.lower()

        # 4. <priority>
        if fixed_priority and fixed_priority != "do not include":
            priority_elem = ET.SubElement(url_elem, "priority")
            priority_elem.text = str(fixed_priority)
        elif auto_priority:
            depth = int(page.get("depth", 0) or 0)
            if depth == 0:
                p = "1.0"
            elif depth == 1:
                p = "0.8"
            elif depth == 2:
                p = "0.6"
            elif depth == 3:
                p = "0.5"
            else:
                p = "0.4"
            priority_elem = ET.SubElement(url_elem, "priority")
            priority_elem.text = p

    rough_string = ET.tostring(urlset, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ", encoding="UTF-8").decode("utf-8")

def build_urllist_txt(pages: list) -> str:
    """Generate simple text urllist.txt sitemap supported by Google and Yahoo."""
    valid_urls = []
    for page in pages:
        url = str(page.get("url", "")).strip()
        status = page.get("status_code", 200)
        is_indexable = page.get("is_indexable", True)
        if url and status == 200 and is_indexable is not False:
            valid_urls.append(url)
    return "\n".join(valid_urls)

def build_html_sitemap(pages: list, target_url: str) -> str:
    """Generate a clean, responsive HTML sitemap for human visitors and footer navigation."""
    valid_pages = [
        p for p in pages 
        if p.get("status_code", 200) == 200 and p.get("is_indexable", True) is not False
    ]
    domain = urlparse(target_url).netloc or "Website"
    date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

    items_html = ""
    for page in sorted(valid_pages, key=lambda x: (int(x.get("depth", 0) or 0), str(x.get("url", "")))):
        url = page.get("url", "")
        title = str(page.get("title", "") or "").strip() or url
        items_html += f'      <li style="margin-bottom:8px;"><a href="{url}" style="color:#2563EB; text-decoration:none; font-weight:500;">{title}</a> <span style="color:#64748B; font-size:0.85em;">({url})</span></li>\n'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HTML Sitemap - {domain}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; max-width: 960px; margin: 40px auto; padding: 0 20px; color: #1E293B; }}
    h1 {{ font-size: 2rem; color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 12px; }}
    .meta {{ font-size: 0.9rem; color: #64748B; margin-bottom: 24px; }}
    ul {{ list-style-type: disc; padding-left: 24px; }}
    a:hover {{ text-decoration: underline !important; }}
    .footer {{ margin-top: 40px; font-size: 0.85rem; color: #94A3B8; border-top: 1px solid #E2E8F0; padding-top: 12px; }}
  </style>
</head>
<body>
  <h1>HTML Sitemap for {domain}</h1>
  <div class="meta">Generated by Amir's SEO Suite on {date_str} • {len(valid_pages)} Total Pages</div>
  <ul>
{items_html}  </ul>
  <div class="footer">Created with Amir's High-Speed SEO Spider & Sitemap Generator</div>
</body>
</html>"""
    return html

def build_gzipped_xml(xml_content: str) -> bytes:
    """Compress XML sitemap into a valid .xml.gz byte stream."""
    out = io.BytesIO()
    with gzip.GzipFile(fileobj=out, mode="wb") as f:
        f.write(xml_content.encode("utf-8"))
    return out.getvalue()
