[theme]
primaryColor = "#FFC107"
backgroundColor = "#0B0E14"
secondaryBackgroundColor = "#121620"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
